{{- /* 
When basic authentication is enabled and no existing secret is specified,
then a new secret will be created to hold the basic auth configutaion.
*/ -}}
{{- if .Values.mlflow.trackingServer.basicAuth.enabled -}}
{{- if not .Values.mlflow.trackingServer.basicAuth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.basicAuthSecretName" . }}
stringData:
  {{- $dbUri := (printf "postgresql://%s:%s@%s:%s/%s" .Values.postgres.auth.username .Values.postgres.auth.password (printf "%s-postgres-rw" (include "mlflow.fullname" .)) "5432" .Values.postgres.embedded.initdb.database) }}
  {{- if .Values.postgres.external.enabled }}
  {{- $dbUri = (printf "postgresql://%s:%s@%s:%s/%s" .Values.postgres.auth.username .Values.postgres.auth.password .Values.postgres.external.host .Values.postgres.external.port .Values.postgres.external.database) }}
  {{- end }}
  {{- with .Values.mlflow.trackingServer.basicAuth.createSecret }}
  basic_auth.ini: |
    [mlflow]
    default_permission = {{ .defaultPermission }}
    database_uri = {{ $dbUri }}
    admin_username = {{ .adminUsername }}
    admin_password = {{ .adminPassword }}
    authorization_function = {{ .authorizationFunction }}
  {{- end }}
{{- end }}
{{- end }}
