apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: 'powerdns'
spec:
  descriptor:
    links:
      - description: Open App
        url: 'http://{{repl ConfigOption "powerdns_host" }}'
