apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: powerdns
spec:
  title: PowerDNS
  icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
  statusInformers:
    - deployment/powerdns-authoritative
    - deployment/powerdns-recursor
    - deployment/powerdns-admin
