apiVersion: v2
name: mlflow
description: A Helm chart for MLflow - Open source platform for the machine learning lifecycle.
type: application
version: "0.5.2"
appVersion: "3.3.2"
home: https://github.com/mlflow/mlflow/tree/master/charts/mlflow
sources:
  - https://github.com/mlflow/mlflow/tree/master/charts/mlflow
dependencies:
- name: replicated
  version: "^1.1.0"
  repository: "oci://registry.replicated.com/library"
  condition: replicated.enabled
