apiVersion: v2
name: storagebox
description: A Helm chart for different storage options
type: application
version: 0.18.0
appVersion: 1.0.0
dependencies:
- name: replicated
  version: "~1.12.2"
  repository: "oci://registry.replicated.com/library"
  condition: replicated.enabled
- name: cassandra
  version: "~12.3.11"
  repository: https://charts.bitnami.com/bitnami
  condition: cassandra.enabled
- name: nfs-server
  version: "~1.1.2"
  repository: https://charts.obeone.cloud
  condition: nfs-server.enabled
- name: tenant
  version: "7.1.1"
  repository: https://operator.min.io
  condition: tenant.enabled
- name: rqlite
  version: "2.0.0"
  repository: https://rqlite.github.io/helm-charts
  condition: rqlite.enabled
