---
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config
spec:
  groups:
  # cassandra settings
  - name: cassandra_settings
    title: Cassandra Settings
    items:
    - name: cassandra_enabled
      title: Enable Cassandra
      type: bool
      default: false
      required: true
      description: Enable Cassandra
    - name: cassandra_user
      title: Cassandra User
      type: text
      default: cassandra
      required: true
      description: The username to use for the Cassandra user
    - name: cassandra_password
      title: Cassandra Password
      type: password
      default: cassandra
      required: true
      description: The password to use for the Cassandra user
      secret: true
    - name: cassandra_truststore_password
      title: Cassandra Truststore Password
      type: password
      default: cassandra
      required: true
      description: The password to use for the Cassandra truststore
      secret: true
    - name: cassandra_keystore_password
      title: Cassandra Keystore Password
      type: password
      default: cassandra
      required: true
      description: The password to use for the Cassandra keystore
      secret: true
  - name: cassandra_ingress_settings
    title: Cassandra Ingress Settings
    items:
    - name: cassandra_tls_type
      title: Cassandra TLS Type
      type: select_one
      default: "cassandra_no_ssl"
      required: true
      items:
      - name: cassandra_no_ssl
        title: TLS client encryption disabled
      - name: "cassandra_self_signed_ca"
        title: Autogenerate self-signed CA and certificates
      - name: "cassandra_external_ca"
        title: Use external CA and certificates
    - name: cassandra_ingress_host
      title: Cassandra TLS Hostname
      type: text
      default: cassandra.example.com
      required: true
      description: The hostname to use for the Cassandra ingress
      when: 'repl{{ ConfigOptionEquals "cassandra_tls_type" "cassandra_self_signed_ca" }}'
    - name: cassandra_tls_cert
      title: Cassandra TLS Certificate
      type: file
      description: The TLS certificate to use for the Cassandra client encryption
      required: true
      when: 'repl{{ ConfigOptionEquals "cassandra_tls_type" "cassandra_external_ca" }}'
    - name: cassandra_tls_key
      title: Cassandra TLS Key
      type: file
      description: The TLS key to use for the Cassandra client encryption
      secret: true
      required: true
      when: 'repl{{ ConfigOptionEquals "cassandra_tls_type" "cassandra_external_ca" }}'
    - name: cassandra_tls_ca
      title: Cassandra TLS CA
      type: file
      description: The root CA to use for the Cassandra client encryption
      required: true
      when: 'repl{{ ConfigOptionEquals "cassandra_tls_type" "cassandra_external_ca" }}'
  # Postgres settings
  - name: postgres_settings
    title: Postgres database settings
    items:
    - name: postgres_enabled
      title: Enable Postgres
      type: bool
      default: false
      required: true
      description: Enable Postgres
    - name: postgres_user
      title: Postgres User
      type: text
      default: postgres
      required: true
      description: The username for the Postgres user
    - name: postgres_password
      title: Postgres Password
      type: password
      default: postgres
      required: true
      description: Postgres user password
      secret: true
    - name: postgres_db
      title: Postgres Database Name
      type: text
      default: postgres
      required: true
      description: The name of the Postgres database
    - name: postgres_db_owner
      title: Postgres Database Owner
      type: text
      default: postgres
      required: true
      description: The name of the Postgres database owner
  # NFS Server settings
  - name: nfs_settings
    title: NFS Server settings
    items:
    - name: nfs_enabled
      title: Enable NFS Server
      type: bool
      default: false
      required: true
      description: Enable NFS Server
    - name: nfs_share
      title: NFS Share
      type: text
      default: /shared
      required: true
      description: The NFS share to mount
    - name: nfs_share_options
      title: NFS Share Options
      type: text
      default: '*(rw,insecure,no_subtree_check,all_squash)'
      required: true
      description: The NFS share options
  # MinIO Tenant settings
  - name: minio_settings
    title: MinIO Tenant settings
    items:
    - name: minio_tenant_enabled
      title: Enable MinIO Tenant
      type: bool
      default: false
      required: true
      description: Enable MinIO Tenant
    - name: minio_tenant_name
      title: MinIO Tenant Name
      type: text
      default: minio
      required: true
      description: The name of the MinIO Tenant
    # - name: minio_tenant_configuration_name
    #   title: MinIO Tenant Configuration Name
    #   type: text
    #   default: minio-env-configuration
    #   required: true
    #   description: The name of the MinIO Tenant Configuration
    - name: minio_tenant_configuration_access_key
      title: MinIO Tenant Configuration Access Key
      type: password
      default: minio
      required: true
      description: The access key for the MinIO Tenant Configuration
    - name: minio_tenant_configuration_secret_key
      title: MinIO Tenant Configuration Secret Key
      type: password
      default: minio123
      required: true
      description: The secret key for the MinIO Tenant Configuration
      secret: true
    - name: minio_tenant_pool_name
      title: MinIO Tenant Pool Name
      type: text
      default: pool-0
      required: true
      description: The name of the MinIO Tenant Pool
    - name: minio_tenant_pool_servers
      title: MinIO Tenant Pool Servers
      type: text
      default: '1'
      required: true
      description: The number of MinIO Tenant Pool Servers
    - name: minio_tenant_pool_volumes_per_server
      title: MinIO Tenant Pool Volumes Per Server
      type: text
      default: '1'
      required: true
      description: The number of MinIO Tenant Pool Volumes Per Server
    - name: minio_tenant_pool_size
      title: MinIO Tenant Pool Size
      type: text
      default: 10Gi
      required: true
      description: The size of the MinIO Tenant Pool
    - name: minio_tenant_pool_storage_class_name
      title: MinIO Tenant Pool Storage Class Name
      type: text
      default: ''
      description: The storage class name for the MinIO Tenant Pool
    - name: minio_tenant_metrics_enabled
      title: MinIO Tenant Metrics Enabled
      type: bool
      default: true
      description: Enable MinIO Tenant Metrics
      required: true
    - name: minio_tenant_metrics_port
      title: MinIO Tenant Metrics Port
      type: text
      default: '9000'
      description: The port for MinIO Tenant Metrics
      required: true
    - name: minio_tenant_metrics_protocol
      title: MinIO Tenant Metrics Protocol
      type: text
      default: http
      description: The protocol for MinIO Tenant Metrics
      required: true
    - name: minio_tenant_bucket_name
      title: MinIO Tenant Bucket Name
      type: text
      default: minio
      required: true
      description: The name of the MinIO Tenant Bucket
    - name: minio_tenant_bucket_object_lock
      title: MinIO Tenant Bucket Object Lock
      type: bool
      default: false
      description: Enable MinIO Tenant Bucket Object Lock
    - name: minio_tenant_bucket_region
      title: MinIO Tenant Bucket Region
      type: text
      default: us-east-1
      description: The region for the MinIO Tenant Bucket
      required: true
    # - name: minio_tenant_user_name
    #   title: MinIO Tenant User Name
    #   type: text
    #   default: minio
    #   required: true
    #   description: The name of the MinIO Tenant User
    # - name: minio_tenant_user_access_key
    #   title: MinIO Tenant User Access Key
    #   type: password
    #   default: minio
    #   required: true
    #   description: The access key for the MinIO Tenant User
    # - name: minio_tenant_user_secret_key
    #   title: MinIO Tenant User Secret Key
    #   type: password
    #   default: minio123
    #   required: true
    #   description: The secret key for the MinIO Tenant User
    #   secret: true
