{{- if .Values.postgres.embedded.enabled -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: powerdns-postgres
spec:
  bootstrap:
    initdb:
      database: {{ .Values.postgres.embedded.initdb.database }}
      owner: {{ .Values.postgres.embedded.initdb.owner }}
      secret:
        name: {{ .Values.postgres.embedded.initdb.secret.name }}
  instances: 1
  imageName: "{{ .Values.postgres.embedded.image.repository }}:{{ .Values.postgres.embedded.image.tag }}"
  imagePullPolicy: {{ .Values.postgres.embedded.imagePullPolicy }}
  {{- with .Values.postgres.embedded.imagePullSecrets}}
  imagePullSecrets:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  postgresUID: {{ .Values.postgres.embedded.postgresUID }}
  postgresGID: {{ .Values.postgres.embedded.postgresGID }}
  storage:
    size: {{ .Values.postgres.embedded.storage.size }}
    storageClass: {{ .Values.postgres.embedded.storage.storageClass }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{ end }}
  {{- with .Values.postgres.embedded.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  priorityClassName: {{ .Values.postgres.embedded.priorityClassName }}
  primaryUpdateMethod: {{ .Values.postgres.embedded.primaryUpdateMethod }}
  primaryUpdateStrategy: {{ .Values.postgres.embedded.primaryUpdateStrategy }}
  logLevel: {{ .Values.postgres.embedded.logLevel }}
  {{- with .Values.postgres.embedded.certificates }}
  certificates:
    {{- toYaml . | nindent 4 }}
  {{ end }}
  enableSuperuserAccess: {{ .Values.postgres.embedded.enableSuperuserAccess }}
  {{- with .Values.postgres.embedded.superuserSecret }}
  superuserSecret:
    name: {{ . }}
  {{ end }}
  postgresql:
    shared_preload_libraries:
      {{- if eq .Values.postgres.embedded.type "timescaledb" }}
      - timescaledb
      {{- end }}
    {{- with .Values.postgres.embedded.postgresql }}
    parameters:
      {{- toYaml . | nindent 6 }}
    {{ end }}
  managed:
    {{- with .Values.postgres.embedded.roles }}
    roles:
      {{- toYaml . | nindent 6 }}
    {{ end }}
{{- end -}}
