{{- if and .Values.postgres.embedded.enabled (not .Values.postgres.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}-postgres-initdb-secret
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
{{- end -}}
