{{- if .Values.postgres.embedded.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: gitea-postgres-initdb-secret
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
{{- end -}}
