name: replicated-release-unstable

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push-to-replicated:
    runs-on: ubuntu-22.04
    outputs:
      channel-slug: ${{ steps.create-release.outputs.channel-slug }}
      release-sequence: ${{ steps.create-release.outputs.release-sequence }}
      app-version: ${{ steps.set-release-version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get latest tag
        id: get-latest-tag
        run: |
          # Get the latest tag, defaulting to 0.1.0 if none exists
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.1.0")
          echo "LATEST_TAG=${latest_tag}" >> $GITHUB_ENV

      - name: Set release version
        id: set-release-version
        run: |
          IFS='.' read -r major minor patch <<< "${{ env.LATEST_TAG }}"
          version="${major}.${minor}.$((patch + 1))-Unstable"
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Package Helm chart
        id: package-helm-chart
        run: |
          helm package ./app --debug -u -d ./replicated \
            --version ${{ env.VERSION }} \
            --app-version ${{ env.VERSION }}
      
      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq &&\
          chmod +x /usr/local/bin/yq

      - name: Update HelmChart kind
        run: |
          yq -i '.spec.chart.chartVersion = "${{ env.VERSION }}"' replicated/kots-chart.yaml
      
      - name: Create Replicated release
        id: create-release
        uses: replicatedhq/compatibility-actions/create-release@v1
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          yaml-dir: ./replicated
          promote-channel: Unstable
          version: ${{ env.VERSION }}