{{- if .Values.cassandra.tls.clientEncryption -}}
  {{- $cert := dict -}}
  {{- $ca := dict -}}
  {{- if .Values.cassandra.tls.selfSignedCA -}}
    {{- $ca = genCA "cassandra-ca" 730 -}}
    {{- $cert = genSignedCert "cassandra-client" nil nil 730 $ca -}}
  {{- else -}}
    {{- $_ := set $ca "CA" .Values.cassandra.tls.ca -}}
    {{- $_ := set $cert "Cert" .Values.cassandra.tls.cert -}}
    {{- $_ := set $cert "Key" .Values.cassandra.tls.key -}}
  {{- end -}}
apiVersion: v1
data:
  ca.crt: {{ $ca.CA }}
  tls.crt: {{ $cert.Cert  }}
  tls.key: {{ $cert.Key  }}
kind: Secret
metadata:
  name: cassandra-crt
  labels:
    {{- include "cassandra.labels" . | nindent 4 }}
type: kubernetes.io/tls
{{- end -}}
