name: traefik
version: 1.0.0
appVersion: latest
apiVersion: v2
dependencies:
  - name: traefik
    version: '28.0.0'
    repository: https://traefik.github.io/charts
  - name: templates
    version: '*'
    repository: file://../templates
