{{- if .Values.cassandra.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-superuser-secret
  labels:
    {{- include "storagebox.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cassandra.auth.username | quote }}
  password: {{ .Values.cassandra.auth.password | quote }}
{{- end -}}
