{{- if .Values.postgres.embedded.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  name: powerdns-postgres-auth
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.auth.username }}
  password: {{ .Values.postgres.auth.password }}
{{- end }}
