apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flipt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/flipt-config.yaml") . | sha256sum }}
    {{- if .Values.deploymentAnnotations }}
    {{- toYaml .Values.deploymentAnnotations | nindent 4 }}
    {{- end }}
    {{- if eq .Values.postgresql.type "embedded" }}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "10"
    helm.sh/resource-policy: keep
    {{- end }}
  labels:
    {{- include "flipt.labels" . | nindent 4 }}
    {{- if .Values.deploymentLabels }}
    {{- toYaml .Values.deploymentLabels | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 8 }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "flipt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: {{- include "common.classes.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "flipt.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end}}
      serviceAccountName: {{ include "flipt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          {{- toYaml .Values.image.command | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.httpPort }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.service.httpsPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.config.server.grpcPort }}
              protocol: TCP
          env:
            - name: FLIPT_META_STATE_DIRECTORY
              value: /home/flipt/.config/flipt
            - name: FLIPT_META_CHECK_FOR_UPDATES
              value: "0"
            {{- if eq .Values.postgresql.type "embedded" }}
            - name: FLIPT_DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "flipt.postgresql.clustername" . }}-app
                  key: uri
            {{- end }}
            {{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
            - name: FLIPT_CACHE_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "flipt.redis.secret" . }}
                  key: redis-password
            {{- end }}
            {{- if .Values.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: flipt-local-state
              mountPath: /home/flipt/.config/flipt
            - name: flipt-config
              mountPath: /etc/flipt/config/default.yml
              readOnly: true
              subPath: default.yml
            - name: flipt-data
              mountPath: /var/opt/flipt
            {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: flipt-local-state
          emptyDir: {}
        - name: flipt-config
          configMap:
            name: {{ include "flipt.fullname" . }}
        - name: flipt-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (include "flipt.fullname" .) .Values.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
