{{- if and (eq .Values.postgresql.type "external") .Values.postgresql.external.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flipt.fullname" . }}-postgresql-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flipt.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.postgresql.external.host | quote }}
  port: {{ .Values.postgresql.external.port | quote }}
  database: {{ .Values.postgresql.external.database | quote }}
  username: {{ .Values.postgresql.external.username | quote }}
  password: {{ .Values.postgresql.external.password | quote }}
  sslMode: {{ .Values.postgresql.external.sslMode | quote }}
  url: {{ include "flipt.postgresql.url" . | quote }}
{{- end }}
