apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-preflights
  labels:
    troubleshoot.sh/kind: preflight
type: Opaque
stringData:
  preflight.yaml: |
{{ include "flipt.preflight" . | indent 4 }}
