apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-supportbundle
  labels:
    troubleshoot.sh/kind: support-bundle
type: Opaque
stringData:
  support-bundle-spec: |
{{ include "flipt.supportbundle" . | indent 4 }}
