apiVersion: v2
appVersion: 1.22.3
dependencies:
- name: valkey
  version: "0.9.3"
  repository: "https://valkey.io/valkey-helm/"
  condition: valkey.enabled
description: Gitea Helm chart for Kubernetes
icon: https://gitea.com/assets/img/logo.svg
keywords:
- git
- issue tracker
- code review
- wiki
- gitea
- gogs
maintainers:
- email: charlie@charliedrage.com
  name: Charlie Drage
- email: maintainers@gitea.io
  name: Gitea Authors
- email: konrad.lother@novum-rgi.de
  name: Konrad Lother
- email: lucas.hahn@novum-rgi.de
  name: Lucas Hahn
- email: sk.bunsenbrenner@gmail.com
  name: Steven Kriegler
- email: patrick.schratz@gmail.com
  name: Patrick Schratz
name: gitea
sources:
- https://gitea.com/gitea/helm-chart
- https://github.com/go-gitea/gitea
- https://hub.docker.com/r/gitea/gitea/
type: application
version: 11.0.0
